# -*- coding: utf-8 -*-
"""
/***************************************************************************
 spiutility
                                 A QGIS plugin
 Generates SPI values from Daily Precipiation Rasters
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-19
        copyright            : (C) 2021 by Manaruchi Mohapatra, Dr. Bhaskar R Nikam, Gunjan Kour
        email                : manaruchimohapatra@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load spiutility class from file spiutility.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spiutility import spiutility
    return spiutility(iface)
